LDPLAYER_ROOT: C:\LDPlayer\LDPlayer9
device_name: emulator-5554 # 雷电模拟器默认主设备名, 如果使用多开器, 请自行确定


auto_expedition: True # 自动重复远征
auto_gain_bonus: True # 当有任务完成时自动点击
auto_bath_repair: True # 空闲时自动澡堂修理

auto_battle: True # 自动打完每日战役次数
battle_type: "困难潜艇" # 打哪个。可选名称参考"plans/battle/"

dock_full_destroy: True # 船坞已满时自动清空，若设置为false则船坞已满后终止所有常规出征任务
auto_normal_fight: # 自动出征任务用列表 [plan名，舰队号，目标成功次数] 表示，按顺序从上往下执行。plan名参考"plans/normal_fight/"
  - [8-5AI, 2, 0]
